// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthWind.BlazingPizza.DBAdmin.DataContext;

#nullable disable

namespace NorthWind.BlazingPizza.DBAdmin.Migrations
{
    [DbContext(typeof(BlazingPizzaContext))]
    [Migration("20240607023948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NorthWind.BlazingPizza.Backend.Repositories.Entities.PizzaSpecial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PizzaSpecials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 89.99m,
                            Description = "Es de queso y delicioso. ¿Por qué no querrías una?",
                            ImageUrl = "cheese.jpg",
                            Name = "Pizza clásica de queso"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 127.99m,
                            Description = "Tiene TODO tipo de tocino",
                            ImageUrl = "bacon.jpg",
                            Name = "Tocinator"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 99.50m,
                            Description = "Es la pizza con la que creciste, ¡pero ardientemente deliciosa!",
                            ImageUrl = "pepperoni.jpg",
                            Name = "Clásica de pepperoni"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 128.75m,
                            Description = "Pollo picante, salsa picante y queso azul, garantizado que entrarás en calor",
                            ImageUrl = "meaty.jpg",
                            Name = "Pollo búfalo"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 109.00m,
                            Description = "Tiene champiñones. ¿No es obvio?",
                            ImageUrl = "mushroom.jpg",
                            Name = "Amantes del champiñón"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 90.25m,
                            Description = "De piña, jamón y queso...",
                            ImageUrl = "hawaiian.jpg",
                            Name = "Hawaiana"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 118.50m,
                            Description = "Es como una ensalada, pero en una pizza",
                            ImageUrl = "salad.jpg",
                            Name = "Delicia vegetariana"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 89.99m,
                            Description = "Pizza italiana tradicional con tomates y albahaca",
                            ImageUrl = "margherita.jpg",
                            Name = "Margarita"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
